version: "3.9"
services:
  app:
    image: node:18.13-alpine3.17
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./:/app
    ports:
      - 127.0.0.1:2500:3000
      - 127.0.0.1:4001:4001
