version: "3.9"
services:
  app:
    image: node:16.15.1-bullseye
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./:/app
    ports:
      - 127.0.0.1:2500:3000
      - 127.0.0.1:4001:4001
